version: '3.8'

services:
  evolution-api:
    image: davidsongomes/evolution-api:latest
    container_name: evolution-api
    ports:
      - "8080:8080"
    environment:
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - SERVER_URL=http://localhost:8080
      - CORS_ORIGIN=*
      - LOG_LEVEL=ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS,WEBSOCKET
      - LOG_COLOR=true
      - LOG_BAILEYS=error
      - DEL_INSTANCE=false
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://postgres:admin123@postgres:5432/evolution_db?schema=evolution_api
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_clickup
      - AUTHENTICATION_API_KEY=clickup_whatsapp_key_2024
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - LANGUAGE=es
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: evolution-postgres
    environment:
      - POSTGRES_DB=evolution_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5433:5432"
    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: evolution-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  evolution_postgres_data:
